### ISSUE TITLE
Let ssh decide its control sockets etc

### ISSUE THREAD

**Issue by tv42** [openssh-rust/openssh#72]
Hi. I have a project where I'm trying to control ssh(&maybe sftp) from a Rust parent process, and I'd love to use your library.

However, the library seems very opinionated about passing `-S` etc options.

How would you feel about an API that lets `ssh` just do what it is configured to do, instead of forcing its hand so much? Right now, the library won't e.g. let me reuse a master connection that was opened from elsewhere.

**Comment by tv42** [comment]
Just to clarify, https://docs.rs/openssh/0.9.0/openssh/struct.SessionBuilder.html#method.control_directory isn't the right thing, because 1) it still enforces its conventions on putting a te

**Comment by NobodyXu** [comment]
> 1) it just sets the directory to create .ssh-connection<RANDOM>/master

On most cases, it will actually create the socket [`dirs::state_dir`](https://docs.rs/dirs/4.0.0/dirs/fn.state_dir.html), which typically is somewhere in `/var/tmp`, which is called in [`get_default_control_dir`](https://docs.rs/openssh/0.9.0/src/openssh/builder.rs.html#22)

> 2) it doesn't match what my ssh_config does ControlPath /run/user/%i/ssh-master.%r@%h:%p.sock

That will create conflicts as [`Session::close`](https://docs.rs/openssh/0.9.0/openssh/struct.Session.html#method.close) and its `Drop::drop` implementation will request graceful shutdown of the multiplex master.

Reusing the default `ControlPath` might introduce some race condition, creating some strange race condition/bugs that cannot happen now.

**Comment by jonhoo** [comment]
I do think there might be some value to allowing the library to "resume" a connection that was already established elsewhere. I don't think we want to completely give up control over the `ssh` arguments, but a constructor that lets you say "here's a pre-established master connection" does make some amount of sense to me.

@NobodyXu is right though that this API is likely to get you into trouble if you have other processes that _also_ use the same connection, since either may shut down the connection without the other knowing. I think that's something we should document well in such a new API if added. We should likely also add a mechanism for telling the library _not_ to close the master connection when it shuts down.

**Comment by NobodyXu** [comment]
@jonhoo I can add a new method in `Session` to "resume" from a existing control path and simply add a `bool` to `Session` to prevent shutting down of the control master on `drop`.

IMO if we are going to allow users to resume from a existing control path, we should also allow them to use the default control path without shutting down the control master on `drop` and also add the functionality to "yield" the control master.

**Comment by jonhoo** [comment]
That seems reasonable!

**Comment by NobodyXu** [comment]
@tv42 #80 now enables you to resume from any control socket.

To reuse the system-wide control socket, you can use [this SSO answer](https://serverfault.com/questions/140023/can-i-make-ssh-tell-me-which-control-file-it-would-use-for-multiplexing):

```bash
ssh -O check HOST
```

This can be used to find the control socket if it is not yet present.
You can use the path received and pass it to `SessionBuilder`.

```bash
ssh -G HOST | grep controlpath
```

This one can be used to find the control socket if it is already
present and can be passed to `Session::resume_mux` to reuse
the existing control socket.
