### ISSUE TITLE
[Question] Letting the os pick a port?

### ISSUE THREAD

**Issue by alakhpc** [openssh-rust/openssh#92]
Hi!, I'm using this crate to forward a remote socket like this 

```rs
    session
        .request_port_forward(
            ForwardType::Local,
            SocketAddr::from_str("127.0.0.1:0").unwrap(),
            Path::new("/var/run/docker.sock"),
        )
        .await
        .unwrap();
``` 

I'd like to forward to `127.0.0.1:0` to let the os pick any free port,
Is it then possible to get the port number? Thanks!

**Comment by NobodyXu** [comment]
According to [this SSO answer](https://superuser.com/questions/919808/why-ssh-r-allows-port-0-but-ssh-l-needs-a-port-number), this worked only for remote port forwarding and it will print the port to stdout.

So yeah, it should be doable, but I have to fully investigate its actual behavior first and I will add a new API specifically for this scenario.

**Comment by alakhpc** [comment]
For now this is a quick way to do it
```rs
        let port = {
            let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await?;
            listener.local_addr()?.port()
        };
```

**Comment by NobodyXu** [comment]
> For now this is a quick way to do it
> 
> ```rust
>         let port = {
>             let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await?;
>             listener.local_addr()?.port()
>         };
> ```

Note that this contains a race condition, the port could be taken by other processes.

Also, this works only on local port forwarding and not remote port forwarding.

@alakhpc Looks like you are using `127.0.0.1:0` for local port forwarding?
Then even `ssh` cannot help here since it only supports using random port for remote port forwarding.
Checkout [this SSO answer](https://superuser.com/questions/919808/why-ssh-r-allows-port-0-but-ssh-l-needs-a-port-number)

**Comment by NobodyXu** [comment]
@alakhpc I would recommend you to use unix socket.

You can use [`tempfile`](https://docs.rs/tempfile) to create a `TempPath` and then forward a local unix socket in it to remote port.

That means it is extremely unlikely to be accidentally occupied by others, since only privileged processes and ones with the same uid can modify that path.

It is also safer since only privileged processes and ones with the same uid can connect to it.

**Comment by alakhpc** [comment]
Thanks!, yeah using sockets definitely seems to be the better way, however im having some trouble getting it started
```rs
        let socket = NamedTempFile::new()?;
        let listen_socket = socket.into_temp_path();
        let connect_socket = Path::new("/var/run/docker.sock");

        session
            .request_port_forward(ForwardType::Local, &*listen_socket, connect_socket)
            .await?;
```
> Could not connect to ssh server: failed to connect to the ssh multiplex server

I tried a regular file too instead of a tempfile, but still the same.

Im basically trying to forward requests from a local socket to /var/run/docker.sock on a remote machine.

**Comment by NobodyXu** [comment]
@alakhpc You need to remove the file using `std::fs::remove` since `NamedTempFile` actually creates a file there.

**Comment by alakhpc** [comment]
Thanks!, I'm already using `SessionBuilder::connect_mux`

```rs
        let session = SessionBuilder::default()
            .user(self.user.clone())
            .port(self.port)
            .known_hosts_check(KnownHosts::Add)
            .control_directory(std::env::temp_dir())
            .connect_timeout(Duration::from_secs(5))
            .connect_mux(&self.ip)
            .await?;
```

**Comment by alakhpc** [comment]
It seems to be working after removing the file! thanks!,

**Comment by NobodyXu** [comment]
Closing as resolved.
